
import { VaxInfo } from './types';

export const VACCINE_SCHEDULE: VaxInfo[] = [
  { key: 'bcg', name: 'BCG', age: 0, description: 'ការពារជំងឺរបេង' },
  { key: 'hepb0', name: 'Hepatitis B (Dose 0)', age: 0, description: 'ការពារជំងឺរលាកថ្លើមប្រភេទ B' },
  { key: 'dtap1', name: 'DTaP (Dose 1)', age: 2, description: 'ខាន់ស្លាក់, តេតាណូស, ក្អកមាន់' },
  { key: 'hib1', name: 'Hib (Dose 1)', age: 2, description: 'ការពារជំងឺរលាកស្រោមខួរ' },
  { key: 'polio1', name: 'Polio (Dose 1)', age: 2, description: 'ការពារជំងឺស្វិតដៃជើង' },
  { key: 'pcv1', name: 'PCV13 (Dose 1)', age: 2, description: 'ការពារជំងឺរលាកសួត' },
  { key: 'rota1', name: 'Rotavirus (Dose 1)', age: 2, description: 'ការពារជំងឺរាក' },
  { key: 'dtap2', name: 'DTaP (Dose 2)', age: 4, description: 'ខាន់ស្លាក់, តេតាណូស, ក្អកមាន់' },
  { key: 'hib2', name: 'Hib (Dose 2)', age: 4, description: 'ការពារជំងឺរលាកស្រោមខួរ' },
  { key: 'polio2', name: 'Polio (Dose 2)', age: 4, description: 'ការពារជំងឺស្វិតដៃជើង' },
  { key: 'pcv2', name: 'PCV13 (Dose 2)', age: 4, description: 'ការពារជំងឺរលាកសួត' },
  { key: 'rota2', name: 'Rotavirus (Dose 2)', age: 4, description: 'ការពារជំងឺរាក' },
  { key: 'dtap3', name: 'DTaP (Dose 3)', age: 6, description: 'ខាន់ស្លាក់, តេតាណូស, ក្អកមាន់' },
  { key: 'hib3', name: 'Hib (Dose 3)', age: 6, description: 'ការពារជំងឺរលាកស្រោមខួរ' },
  { key: 'polio3', name: 'Polio (Dose 3)', age: 6, description: 'ការពារជំងឺស្វិតដៃជើង' },
  { key: 'pcv3', name: 'PCV13 (Dose 3)', age: 6, description: 'ការពារជំងឺរលាកសួត' },
  { key: 'hepb1', name: 'Hepatitis B (Dose 1)', age: 6, description: 'ការពារជំងឺរលាកថ្លើមប្រភេទ B' },
  { key: 'flu1', name: 'Influenza (Yearly)', age: 6, description: 'ការពារជំងឺផ្ដាសាយធំ' },
  { key: 'mmr1', name: 'MMR (Dose 1)', age: 12, description: 'កញ្ជ្រឹល, ស្រឡទែន, ស្អូច' },
  { key: 'varicella1', name: 'Varicella (Dose 1)', age: 12, description: 'ការពារជំងឺអុតស្វាយ' },
  { key: 'hepa1', name: 'Hepatitis A (Dose 1)', age: 12, description: 'ការពារជំងឺរលាកថ្លើមប្រភេទ A' },
  { key: 'dtap4', name: 'DTaP (Dose 4)', age: 15, description: 'ខាន់ស្លាក់, តេតាណូស, ក្អកមាន់' },
  { key: 'hib4', name: 'Hib (Dose 4)', age: 15, description: 'ការពារជំងឺរលាកស្រោមខួរ' },
  { key: 'pcv4', name: 'PCV13 (Dose 4)', age: 15, description: 'ការពារជំងឺរលាកសួត' },
  { key: 'hepa2', name: 'Hepatitis A (Dose 2)', age: 18, description: 'ការពារជំងឺរលាកថ្លើមប្រភេទ A (6 ខែបន្ទាប់ពីដូសទី 1)' },
  { key: 'dtap5', name: 'DTaP (Dose 5)', age: 48, description: 'ខាន់ស្លាក់, តេតាណូស, ក្អកមាន់' },
  { key: 'polio4', name: 'Polio (Dose 4)', age: 48, description: 'ការពារជំងឺស្វិតដៃជើង' },
  { key: 'mmr2', name: 'MMR (Dose 2)', age: 48, description: 'កញ្ជ្រឹល, ស្រឡទែន, ស្អូច' },
  { key: 'varicella2', name: 'Varicella (Dose 2)', age: 48, description: 'ការពារជំងឺអុតស្វាយ' },
];
